#! /bin/sh
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#

MAKE="make -j6 MODE=debug"

TESTFILES='*.test'
if [ ! -d work ];  then mkdir work; fi
export NEDPATH=.:../
#OPT="-a --debugger-attach-on-error=true"

$MAKE -C signalreg

opp_test gen $OPT -v $TESTFILES || exit 1
echo
(cd work; opp_makemake -f -o work --deep --no-deep-includes; $MAKE) || exit 1
echo
opp_test run $OPT -p work_dbg -v $TESTFILES || exit 1
echo
echo Results can be found in ./work

