#! /bin/sh
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#

MAKE="make -j6 MODE=debug"
DBG_SUFFIX="_dbg"

TESTFILES='*.test'
if [ ! -d work ];  then mkdir work; fi
export NEDPATH=.:../../../../src
#OPT="-a --debugger-attach-on-error=true"

$MAKE -C signalreg

opp_test gen $OPT -v $TESTFILES || exit 1

echo
(cd work; opp_makemake -f --deep -ltictoc$DBG_SUFFIX -L../../../src -P . --no-deep-includes -I../../../src; $MAKE) || exit 1

echo
PATH=$PATH:../../../src opp_test run $OPT -v -p work$DBG_SUFFIX $TESTFILES -a "--check-signals=false -ltictoc " || exit 1

echo
echo Results can be found in ./work
